---
title: "(Incidence)"
author: "Mustapha Ghazi"
date: "2023-03-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(segmented)
library(seas)
library(readxl)
library(readr)
library(reshape2)
library(data.table)
library(mosaic)
library(modelr)
library(hexbin)
library(nortest)
library(rmarkdown)
library(dplyr)
```

```{r}
setwd("~/Desktop/DATA")
#crudedata1_seer <- read.csv("crudedata1_seer.csv", header = T)
#sheet_1 <- read.csv("sheet 1.csv", header = T)
#sheet_3 <- read.csv("sheet 3.csv", header = T)

Leukemia_Incidence <- read.csv("leukemiaIncidence.csv", header = TRUE)
```

Some data cleaning
```{r}
#base <- crudedata1_seer %>% filter(Sex != 0 & Year.of.death != 0) %>% dplyr::select(Age.recode.with..1.year.olds, Sex, Year.of.death)
#basicData <- base %>% rename("Age Recode (< 1)" = "Age.recode.with..1.year.olds", "Year of Death" = "Year.of.death"); basicData
```

Ages and their distributions
```{r}
ageCount <- Leukemia_Incidence %>% filter(!is.na(Count)) %>% count(Age.recode.with..1.year.olds) ; ageCount # ok so this isnt how many died but rather how many entries we have. Kinda useless unless you wanna descibe your dataset not the information conveyed

sum(ageCount$n) # see, matches the number of rows when leukemiaMortality %>% filter(!is.na(Count)) is done

incidenceAges <- Leukemia_Incidence %>% filter(!is.na(Count)) %>% dplyr::select(Age.recode.with..1.year.olds, Count) %>% group_by(Age.recode.with..1.year.olds) %>% count(Age.recode.with..1.year.olds, wt=Count) %>% rename("Age (recode with < 1 years old)" = "Age.recode.with..1.year.olds", "Count" = "n"); incidenceAges

n <- sum(incidenceAges$Count)

incidenceAges <- mutate(incidenceAges, Percent = 100*Count/n); incidenceAges

ggplot(incidenceAges, aes(incidenceAges$'Age (recode with < 1 years old)')) + geom_bar(aes(weight = Count)) + ylab("Count") + xlab("Age (recode with < 1 years old)") + ggtitle("Incidence by Age Group")

ggplot(incidenceAges, aes(x = `Age (recode with < 1 years old)`, y = Count)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = Count), hjust = -0.5)  + coord_flip() + 
  scale_x_continuous(breaks = seq(0, 100, by = 10)) +
  scale_y_continuous(labels = function(x) format(x, scientific=FALSE)) +
  ylab("Count") +
  xlab("Age (recode with < 1 years old)") +
  ggtitle("Incidence by Age Group")
```

Sex and their distributions
```{r}
sexCount <- Leukemia_Incidence %>% filter(!is.na(Count)) %>% count(Sex) ; sexCount # ok so this isnt how many died but rather how many entries we have. Kinda useless unless you wanna descibe your dataset not the information conveyed

sum(sexCount$n) # see, matches the number of rows when leukemiaMortality %>% filter(!is.na(Count)) is done

incidenceSex <- Leukemia_Incidence %>% filter(!is.na(Count)) %>% dplyr::select(Sex, Count) %>% group_by(Sex) %>% count(Sex, wt=Count) %>% rename("Count" = "n"); incidenceSex

n <- sum(incidenceSex$Count)

incidenceSex <- mutate(incidenceSex, Percent = 100*Count/n); incidenceSex

ggplot(incidenceSex, aes(Sex)) + geom_bar(aes(weight = Count)) + ylab("Count") + xlab("Sex") + ggtitle("Incidences by Sex Group")
```

State and their distributions (no states)
#```{r}
stateCount <- Leukemia_Incidence %>% filter(!is.na(Count)) %>% count(State) ; stateCount # ok so this isnt how many died but rather how many entries we have. Kinda useless unless you wanna descibe your dataset not the information conveyed

sum(stateCount$n) # see, matches the number of rows when leukemiaMortality %>% filter(!is.na(Count)) is done

incidenceState <- Leukemia_Incidence %>% filter(!is.na(Count)) %>% dplyr::select(State, Count) %>% group_by(State) %>% count(State, wt=Count) %>% rename("Count" = "n"); incidenceState

n <- sum(incidenceState$Count)

incidenceState <- mutate(incidenceState, Percent = 100*Count/n); incidenceState

incidenceState$State <- as.character(incidenceState$State)

ggplot(incidenceState, aes(State)) + geom_bar(aes(weight = Count)) + ylab("Count") + xlab("State") + ggtitle("Incidences by State") + coord_flip()
#```


YOI and their distributions (maybe group these similarly to mortality)
```{r}
yoiCount <- Leukemia_Incidence %>% filter(!is.na(Count)) %>% count(Year.of.diagnosis) ; yoiCount # ok so this isnt how many died but rather how many entries we have. Kinda useless unless you wanna descibe your dataset not the information conveyed

sum(yoiCount$n) # see, matches the number of rows when leukemiaMortality %>% filter(!is.na(Count)) is done

incidenceYOI <- Leukemia_Incidence %>% filter(!is.na(Count)) %>% filter(Year.of.diagnosis != 0) %>% dplyr::select(Year.of.diagnosis, Count) %>% group_by(Year.of.diagnosis) %>% count(Year.of.diagnosis, wt=Count) %>% rename("Count" = "n"); incidenceYOI

n <- sum(incidenceYOI$Count)

incidenceYOI <- mutate(incidenceYOI, Percent = 100*Count/n); incidenceYOI

ggplot(incidenceYOI, aes(Year.of.diagnosis)) + geom_bar(aes(weight = Count)) + ylab("Count") + xlab("Year of Incidence") + ggtitle("Incidences by Year of Incidence") + coord_flip()
```

Race and their distributions
```{r}
raceCount <- Leukemia_Incidence %>% filter(!is.na(Count)) %>% count(Race.recode..White..Black..Other.) ; raceCount # ok so this isnt how many died but rather how many entries we have. Kinda useless unless you wanna descibe your dataset not the information conveyed

sum(raceCount$n) # see, matches the number of rows when leukemiaMortality %>% filter(!is.na(Count)) is done

incidenceRace <- Leukemia_Incidence %>% filter(!is.na(Count)) %>% dplyr::select(Race.recode..White..Black..Other., Count) %>% group_by(Race.recode..White..Black..Other.) %>% count(Race.recode..White..Black..Other., wt=Count) %>% rename("Count" = "n"); incidenceRace

n <- sum(incidenceRace$Count)

incidenceRace <- mutate(incidenceRace, Percent = 100*Count/n); incidenceRace

ggplot(incidenceRace, aes(Race.recode..White..Black..Other.)) + geom_bar(aes(weight = Count)) + ylab("Count") + xlab("Race") + ggtitle("Incidences by Race") + coord_flip()
```

New data with words
```{r}
leukemiaIncidence2 <- read.csv("leukemiaIncidence2.csv", header = TRUE); 
leukemiaIncidence2 <- leukemiaIncidence2 %>% 
   mutate(Race = ifelse(Race == 0, "All", 
                        ifelse(Race == 1, "White", 
                        ifelse(Race == 2, "Black",
                        ifelse(Race == 3, "Other", "Unspecified"))))) %>%
   mutate(Age.Group = ifelse(Age.Group == 0, "00 years", 
                        ifelse(Age.Group == 1, "01-04 years", 
                        ifelse(Age.Group == 2, "05-09 years",
                        ifelse(Age.Group == 3, "10-14 years",
                        ifelse(Age.Group == 4, "15-19 years", 
                        ifelse(Age.Group == 5, "20-24 years",
                        ifelse(Age.Group == 6, "25-29 years",
                        ifelse(Age.Group == 7, "30-34 years", 
                        ifelse(Age.Group == 8, "35-39 years",
                        ifelse(Age.Group == 9, "40-44 years",
                        ifelse(Age.Group == 10, "45-49 years", 
                        ifelse(Age.Group == 11, "50-54 years",
                        ifelse(Age.Group == 12, "55-59 years",  
                        ifelse(Age.Group == 13, "60-64 years", 
                        ifelse(Age.Group == 14, "65-69 years",
                        ifelse(Age.Group == 15, "70-74 years",
                        ifelse(Age.Group == 16, "75-79 years", 
                        ifelse(Age.Group == 17, "80-84 years",
                        ifelse(Age.Group == 18, "85+ years", "Unknown"))))))))))))))))))))  %>%
   mutate(Year.of.diagnosis = ifelse(Year.of.diagnosis == 0, "1975-2019", 
                        ifelse(Year.of.diagnosis == 1, "1975-1977", 
                        ifelse(Year.of.diagnosis == 2, "1975-1977",
                        ifelse(Year.of.diagnosis == 3, "1975-1977",
                        ifelse(Year.of.diagnosis == 4, "1978-1980", 
                        ifelse(Year.of.diagnosis == 5, "1978-1980",
                        ifelse(Year.of.diagnosis == 6, "1978-1980",
                        ifelse(Year.of.diagnosis == 7, "1981-1983", 
                        ifelse(Year.of.diagnosis == 8, "1981-1983",
                        ifelse(Year.of.diagnosis == 9, "1981-1983",
                        ifelse(Year.of.diagnosis == 10, "1984-1986", 
                        ifelse(Year.of.diagnosis == 11, "1984-1986",
                        ifelse(Year.of.diagnosis == 12, "1984-1986",  
                        ifelse(Year.of.diagnosis == 13, "1987-1989", 
                        ifelse(Year.of.diagnosis == 14, "1987-1989",
                        ifelse(Year.of.diagnosis == 15, "1987-1989",
                        ifelse(Year.of.diagnosis == 16, "1990-1992", 
                        ifelse(Year.of.diagnosis == 17, "1990-1992",
                        ifelse(Year.of.diagnosis == 18, "1990-1992",
                        ifelse(Year.of.diagnosis == 19, "1993-1995", 
                        ifelse(Year.of.diagnosis == 20, "1993-1995",
                        ifelse(Year.of.diagnosis == 21, "1993-1995",
                        ifelse(Year.of.diagnosis == 22, "1996-1998", 
                        ifelse(Year.of.diagnosis == 23, "1996-1998",
                        ifelse(Year.of.diagnosis == 24, "1996-1998",
                        ifelse(Year.of.diagnosis == 25, "1999-2001", 
                        ifelse(Year.of.diagnosis == 26, "1999-2001",
                        ifelse(Year.of.diagnosis == 27, "1999-2001",  
                        ifelse(Year.of.diagnosis == 28, "2002-2004", 
                        ifelse(Year.of.diagnosis == 29, "2002-2004",
                        ifelse(Year.of.diagnosis == 30, "2002-2004",
                        ifelse(Year.of.diagnosis == 31, "2005-2007",
                        ifelse(Year.of.diagnosis == 32, "2005-2007", 
                        ifelse(Year.of.diagnosis == 33, "2005-2007",
                        ifelse(Year.of.diagnosis == 34, "2008-2010",
                        ifelse(Year.of.diagnosis == 35, "2008-2010", 
                        ifelse(Year.of.diagnosis == 36, "2008-2010",
                        ifelse(Year.of.diagnosis == 37, "2011-2013",
                        ifelse(Year.of.diagnosis == 38, "2011-2013", 
                        ifelse(Year.of.diagnosis == 39, "2011-2013",
                        ifelse(Year.of.diagnosis == 40, "2014-2016",
                        ifelse(Year.of.diagnosis == 41, "2014-2016", 
                        ifelse(Year.of.diagnosis == 42, "2014-2016", "2017-2019")))))))))))))))))))))))))))))))))))))))))))) %>%
   mutate(Sex = ifelse(Sex == 0, "Male and female", 
                        ifelse(Sex == 1, "Male", "Female")))

write.csv(leukemiaIncidence2, "leukemiaIncidenceDescription.csv", row.names=FALSE)
```


Redoing all the graphs with the Description data

```{r}
leukemiaIncidenceDesc <- read.csv("leukemiaIncidenceDescription.csv", header = TRUE);

incidenceAges2 <- leukemiaIncidenceDesc %>% filter(!is.na(Count)) %>% filter(Age.Group != 'Unknown')  %>% filter(Race == "All") %>% filter(Sex == "Male and female") %>% dplyr::select(Age.Group, Count) %>% group_by(Age.Group) %>% count(Age.Group, wt=Count) %>% rename("Count" = "n"); incidenceAges2

n <- sum(incidenceAges2$Count)

incidenceAges2 <- mutate(incidenceAges2, Percent = 100*Count/n); incidenceAges2

ggplot(incidenceAges2, aes(x = Age.Group, y = Count, fill = Age.Group)) +
  geom_bar(stat = "identity")  + coord_flip() +
  scale_y_continuous(labels = function(x) format(x, scientific=FALSE)) +
  ylab("Count") +
  xlab("Age (recode with < 1 years old)") + theme(legend.position="none") + 
  ggtitle("Incidences by Age Group")
```

```{r}
incidenceSex2 <- leukemiaIncidenceDesc %>% filter(!is.na(Count)) %>% filter(Sex != 'Male and female')  %>% filter(Race == "All") %>% dplyr::select(Sex, Count) %>% group_by(Sex) %>% count(Sex, wt=Count) %>% rename("Count" = "n"); incidenceSex2

n <- sum(incidenceSex2$Count)

incidenceSex2 <- mutate(incidenceSex2, Percent = 100*Count/n); incidenceSex2

ggplot(incidenceSex2, aes(Sex, fill = Sex)) + geom_bar(aes(weight = Count)) + ylab("Count") + xlab("Sex") + ggtitle("Incidences by Sex Group") + theme(legend.position="none")
```

```{r}
incidenceYOI2 <- leukemiaIncidenceDesc %>% filter(!is.na(Count))  %>% filter(Race == "All") %>% filter(Sex == "Male and female") %>% filter(Year.of.diagnosis != "1975-2019") %>% dplyr::select(Year.of.diagnosis, Count) %>% group_by(Year.of.diagnosis) %>% count(Year.of.diagnosis, wt=Count) %>% rename("Count" = "n"); incidenceYOI2

n <- sum(incidenceYOI2$Count)

incidenceYOI2 <- mutate(incidenceYOI2, Percent = 100*Count/n); incidenceYOI2

ggplot(incidenceYOI2, aes(Year.of.diagnosis, fill = Year.of.diagnosis)) + geom_bar(aes(weight = Count)) + ylab("Count") + xlab("Year of Diagnosis") + ggtitle("Incidences by Year of Diagnosis") + theme(legend.position="none") + coord_flip()
```

```{r}
incidenceRace2 <- leukemiaIncidenceDesc %>% filter(!is.na(Count)) %>% filter(Race != 'All')  %>% filter(Sex == "Male and female") %>% dplyr::select(Race, Count) %>% group_by(Race) %>% count(Race, wt=Count) %>% rename("Count" = "n"); arrange(incidenceRace2, Count)

n <- sum(incidenceRace2$Count)

incidenceRace2 <- mutate(incidenceRace2, Percent = 100*Count/n); arrange(incidenceRace2, Count)

ggplot(incidenceRace2, aes(reorder(Race, (Count)), fill = Race)) + geom_bar(aes(weight = Count)) + ylab("Count") + xlab("Race") + ggtitle("Incidence by Race") + theme(legend.position="none") +coord_flip()
```

